@startuml connect4_constructorFunction_classdiagram

package "console-mpds" <<Rectangle>> #ccc {
    class console {
        writeln(text)
        readString(question)
        readNumber(question)
    }
}

package "Types" <<Rectangle>> #aca {
    class Coordinate {
        MAX_COLUMNS
        MAX_ROWS
        row
        column
        shifted(coordinate)
        toString()
        isValid()
        getOposite()
    }

    class Direction {
        name
        coordinate
        toString()
        getOpositeCoordinate()
    }
}

package "Model" <<Rectangle>> #aca {
    class Line {
        LENGTH
        direction
        coordinates
        toString()
        shift()
    }

    class Board {
        TOKEN_EMPTY
        tokens
        lastCoordinate
        getMaxRows()
        getMaxColumns()
        getToken(row, column)
        isLastCoordinateColumnEmpty()
        putLastCoordinate(token)
        isComplete()
        isLastTokenInLine()
        isInLine(line)
    }

    class Player{
        color
        getColor()
    }

    class Turn{
        NUMBER_PLAYERS
        activePlayer
        next()
        getToken()
        coordinateColumnEmpty()
        getCoordinate()
        putCoordinate()
    }

    class Game {
        isFinished()
        isWinner()
        getWinnerToken()
        nextTurn()
    }
}

package "Views" <<Rectangle>> #caa {
    class CoordinateView {
        readColumn()
    }

    class BoardView{
        writeTokens()
    }

    class TurnView {
        playTurn()
        getColumn()
    }

    class GameView {
        writeFinish()
        play()
    }

    class YesNoDialog {
        #question
        #answer
        read()
        isAffirmative()
        isNegative()
    }
}

class Connect4 {
    #continueDialog
    play()
}

Coordinate -> Coordinate

CoordinateView -> Coordinate

Direction *-down-> Coordinate

Line -down-> Coordinate
Line -down-> Direction

Board *-down-> Coordinate
Board *-down-> "4" Direction
Board *-down-> Line

BoardView -down-> Board

Turn *-down-> "2" Player
Turn -down-> Board

TurnView -down-> Turn
TurnView *-down-> CoordinateView

Game *-down-> Board
Game *-down-> Turn

GameView *-down-> Game
GameView *-down-> BoardView
GameView *-down-> TurnView

Connect4 -down-> YesNoDialog
Connect4 *-down-> GameView

YesNoDialog .-l-> console
GameView .-l-> console
BoardView .-l-> console
TurnView .-l-> console
CoordinateView .-l-> console

@enduml