@startuml connect4_constructorFunction_classdiagram

package "console-mpds" <<Rectangle>> #ccc {
    class console {
        writeln(text)
        readString(question)
        readNumber(question)
    }
}

package "Types" <<Rectangle>> #aca {
    class Coordinate {
        {static} MIN_COLUMNS
        {static} MAX_COLUMNS
        {static} MAX_ROWS
        -row
        -column
        constructor(row, column)
        shifted(coordinate)
        toString()
        isValid()
        getOposite()
        getRow()
        getColumn()
        setRow(value)
        setColumn(value)
        clone()
    }

    class Direction {
        {static} NORTH
        {static} NORTH_EAST
        {static} EAST
        {static} SOUTH_EAST
        -name
        -coordinate
        constructor(name, coordinate)
        {static} getValues()
        toString()
        getOpositeCoordinate()
        getCoordinate()
        clone()
    }

    class Color {
        {static} RED
        {static} YELLOW
        {static} NULL
        -string;
        constructor(string) 
        getCode()
        {static} values()
        {static} get(ordinal)
    }    
}    

package "Utils" <<Rectangle>> #aca {
    class assert
}   

package "Model" <<Rectangle>> #aca {

    class Board {
        -tokens
        -lastCoordinate
        -winnerLine
        constructor()
        getMaxRows()
        getMaxColumns()
        getLastCoordinate()
        setLastCoordinate(lastCoordinate)
        setTokens(tokens)
        setWinnerLine(winnerLine)
        getToken(row, column)
        isLastCoordinateColumnEmpty()
        putLastCoordinate(token)
        putCoordinate(column, token)
        isComplete()
        isColumnEmpty(column)
        getEmptyColumns()
        isLastTokenInLine()
        -checkLastTokenInLine
        -isInLine(line)
        isFinished()
        toString()
        clone()
    }

    class Game {
        -board
        -turn
        constructor(numPlayers)
        getBoard()
        getTurn()
        isFinished()
        isWinner()
        getWinnerToken()
        nextTurn()
    }

    class Line {
        {static} LENGTH
        -direction
        -coordinates
        toString()
        shift()
        getCoordinates()
        clone()
    }

    class Player{
        -color
        board
        constructor(indexColor,board)
        getColor()
        isCoordinateColumnEmpty()
        getCoordinate()
        putCoordinate()
    }

    class UserPlayer extends Player{
        constructor(color,board)
        accept(visitor) 
    }

    class MachinePlayer extends Player{
        constructor(color,board)
        accept(visitor)
        setColumn()
    }    

    class RandomMachinePlayer extends MachinePlayer{
        constructor(color, board)
        accept(visitor)    
        setColumn()
    }  

    class MinimaxMachinePlayer extends MachinePlayer{
        {static} -MAX_STEPS
        {static} -MAX_COST
        {static} -OTHER_COST 
        {static} -MIN_COST
        -opositeColor
        constructor(color, board)
        accept(visitor)    
        -maximizePlay(steps, board)
        -minimizePlay(steps, board)
        -isEnd(steps, board)
        -getEndCost(board, cost)
    }  

    class Turn{
        {static} NUMBER_PLAYERS
        -players
        -activePlayer
        constructor(board, numOfPlayers)
        next()
        getToken()
        getActivePlayer()
    }
}

package "Views" <<Rectangle>> #caa {
    class BoardView{
        -board
        -console
        constructor(board,console)
        writeTokens()
    }

    class Connect4View {
        -continueDialog
        -numPlayersMenu
        -console
        constructor(console)
        play()
    }

    class CoordinateView {
        -coordinate
        -console
        constructor(coordinate, console)
        -read(title)
        readColumn()
    }

    class GameView {
        -game
        -boardView
        -console
        constructor(numPlayers, console)
        writeFinish()
        play()
    }

    class PlayerView {
        -player
        -console
        constructor(player, console) 
        playTurn()
        visitUserPlayer()
        visitMachinePlayer()
    }

    class YesNoDialog {
        -question
        -answer
        -console
        constructor(question, console)
        read()
        isAffirmative()
        isNegative()
    }

    class Option {
        -title
        -value
        constructor(title, value) 
        getValue()
        getTitle()
    }

    class Menu {
        -console
        -title
        -options
        -answer
        constructor(title, console)
        add(option)
        interact()
        show()
        -showTitle()
        execChoosedOption()
        -readInt(prompt)
        getChoosedOptionValue()
    }

    class NumPlayersMenu extends Menu {
        constructor(console)
        read()
    }

    class ConsoleView {
        writeln(text)
        readString(question)
        readNumber(question)
    }   

    class ConsoleNode extends ConsoleView {
        writeln(text)
        readString(question)
        readNumber(question)
    }

    class ConsoleBrowser extends ConsoleView {
        constructor()
        writeln(text)
        readString(question)
        readNumber(question)
    }

}

Coordinate -> Coordinate

Direction *-down-> Coordinate

Line -down-> "4" Coordinate
Line -down-> Direction

Board *-down-> Coordinate
Board -down-> Direction
Board *-down-> Line
Board -down-> Color

Player -down-> Color

RandomMachinePlayer --> Coordinate
UserPlayer --> assert

Turn *-down-> "2" Player
Turn .-> Board

Player -r-> Board

Game *-down-> Board
Game *-down-> Turn

CoordinateView -> Coordinate

BoardView -down-> Board

PlayerView -down-> Player
PlayerView *-down-> CoordinateView

GameView *-down-> Game
GameView *-down-> BoardView
GameView *-down-> PlayerView

Connect4View -down-> YesNoDialog
Connect4View -down-> NumPlayersMenu
Connect4View *-down-> GameView

Menu --> Option
NumPlayersMenu *-down-> Option

Connect4View .-down-> ConsoleView
YesNoDialog .-right-> ConsoleView
GameView .-down-> ConsoleView
BoardView .-down-> ConsoleView
TurnView .-down-> ConsoleView
CoordinateView .-right-> ConsoleView
Menu .-down-> ConsoleView

ConsoleNode *-down-> console

app *-> ConsoleNode
app *-> Connect4View
appBrowser *-> ConsoleBrowser
appBrowser *-> Connect4View

@enduml